### ISSUE TITLE
MozFest Workshop Preparation

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/pm-peer-pad#15]
## Info

Date: October 27-29
Slack: mozfest.slack.com
Decentralization Space
Length: 60 minutes!
URL: https://github.com/MozillaFoundation/mozfest-program-2017/issues/130

## TODO

- [x] Flights and Accommodation
  - [x] Ask Skylar for help with Accommodation
  - [X] Pedro's flights
  - [x] David's flights
- [ ] Attend a MozFest facilitator session
- [ ] Read [MozFest facilitator's handbook](https://docs.google.com/document/d/1fezzIH8u0Li6pIHMNYDCuUjA_gHpB4Px9eXQo4Ol7es/edit)

## MozFest Facilitator Training Session

Dirk Slater from FabRiders http://www.fabriders.net/ is offering facilitator coaching for Mozfest sessions. You will get tips and advice on designing a session, feedback on your session and your questions answered.

The facilitators call will take place in the MozFest_Public Vidyo room. Follow the instructions in this link to install VidyoDesktop.

Vidyo Room Link - http://v.mozilla.com/flex.html?roomdirect.html&key=wAi4x5Seon

• Thursday, October 5th, 2016 -  10 EDT/ 15:00 BST/ 5pm MSK/ 7:30pm IST
• Wednesday, October 11th, 2016 -10am PDT/ 1pm EDT/ 6pm BST
• Thursday, 19th October 10am BST/ 12pm MSK/ 2:30pm IST
